# Generated by Django 3.2.5 on 2021-10-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='contact',
            field=models.IntegerField(default=''),
        ),
    ]
