# Generated by Django 3.2.5 on 2021-10-07 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_registration_contact'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registration',
            table='registration',
        ),
    ]
